package com.travyn.notification.entity;

public enum NotificationType {
    CHAT_MESSAGE,
    JOIN_APPROVED,
    JOIN_REJECTED,
    JOIN_REQUEST,
    DIRECT_MESSAGE,
    REVIEW_RECEIVED,
    REVIEWS_PUBLISHED,
    REVIEW_AUTO_PUBLISHED,
    SAFETY_CHECK,
    LOCATION_SHARED,
    DESTINATION_ALERT,
    NEW_MEMBER_JOINED,
    MEMBER_LEFT,
    TRIP_INVITE_ACCEPTED,
    TRIP_CANCELLED,
    CANCELLATION_VOTE,
    SETTLEMENT_REQUEST,
    SETTLEMENT_CONFIRMED
}
